# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e69f6a023f77798c40179f0ef25c4d523b267bbc83f5d3aec5b0795d037b3180bea93bad4003ea852492bcff755538c225c720b995534470b21b4788eb8a46d

test:
  secret_key_base: 38efe12e09a3c406c3aac5083d4ea486a6ebb27152f4c02a905692639957647f4b19a0503ca31bcb3cc80b37bd41e2aedc21f0ffc86327f969288b52fa412de2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
